# Generated by Django 3.1.1 on 2020-10-22 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('phone', models.IntegerField(max_length=15)),
                ('email', models.CharField(max_length=50)),
                ('time', models.CharField(max_length=20)),
            ],
        ),
    ]
