# Generated by Django 3.1.1 on 2020-10-22 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bt', '0003_auto_20201022_1317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='sno',
            field=models.AutoField(default='1', primary_key=True, serialize=False),
        ),
    ]
