# Generated by Django 3.1.1 on 2020-10-22 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bt', '0006_auto_20201022_1337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=models.CharField(max_length=15),
        ),
    ]
