# Generated by Django 3.1.1 on 2020-10-22 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bt', '0007_auto_20201022_1354'),
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('fname', models.CharField(max_length=20)),
                ('lname', models.CharField(default='', max_length=20)),
                ('username', models.CharField(max_length=50)),
                ('date', models.DateField(auto_now_add=True)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
    ]
