# Generated by Django 3.1.1 on 2020-10-23 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bt', '0008_register'),
    ]

    operations = [
        migrations.CreateModel(
            name='inquiry',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('property', models.CharField(default='', max_length=50)),
                ('date', models.DateField()),
                ('phone', models.CharField(max_length=15)),
                ('email', models.CharField(max_length=50)),
                ('message', models.CharField(max_length=500)),
            ],
        ),
        migrations.AlterField(
            model_name='contact',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='register',
            name='date',
            field=models.DateField(),
        ),
    ]
